### ISSUE TITLE
`Error: Failed to obtain access token` when opening a project

### ISSUE THREAD

**Issue by corentin-pasquier** [flowforge/flowforge#1524]
### Current Behavior

When I open a project, it opens a new tab with the right URL and I get this error:
![image](https://user-images.githubusercontent.com/18682315/211511945-1fdc2dd4-ba74-4958-8009-b1d4a6395923.png)

### Expected Behavior

I should access NodeRed without trouble, I'm authentified in Flowforge (I guess ?).

### Steps To Reproduce

I put all of the information about my environment in the section below.
I installed my stack using this command:
```
helm upgrade --atomic --install flowforge flowforge/flowforge -f customization.yml
```

I then crerated my account, created a team, and created a project.

### Environment

Installation: self managed

Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

Helm version:
```
version.BuildInfo{Version:"v3.10.3", GitCommit:"835b7334cfe2e5e27870ab3ed4135f136eecc704", GitTreeState:"clean", GoVersion:"go1.19.4"}
```

FlowForge image: flowforge/forge-k8s:1.2.0
NodeRed image: flowforge/node-red

customization.yml used:
```
forge:
  entryPoint: <custom entrypoint>
  domain: sodebo.fr
  https: false
  localPostgresql: true
  projectSelector:
  managementSelector:
  broker:
    enabled: true
    url: mqtt://forge:1883
  email:
    from: <custom email>
    smtp:
      host: <custom host>
```
