### ISSUE TITLE
Allow passing custom CA as part of email setup

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#1748]
### Description

```
email:
   smtp:
     host: mail.example.com
     tls:
      ca:
        - "PEM ENCODED CA CERT"
```

Shouldn't require any code changes, just docs for email setup.

https://stackoverflow.com/a/66868102

Should also document:

```
email:
   smtp:
     host: mail.example.com
     tls:
       rejectUnauthorized: false
```

As a workaround.
