### ISSUE TITLE
Mirgrations applied on every start on PostrgreSQL

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#357]
### Current Behavior

When using a PostgreSQL database the migration code tries to run even for an empty database or for already up to date database

### Expected Behavior

Migrations only get applied when needed

### Steps To Reproduce

Start FlowForge configured with a PostgreSQL database.

It looks like 

https://github.com/flowforge/flowforge/blob/de3e0d724b7a6db6701383e8720df50037d65d8e/forge/db/migrations/index.js#L43

Always returns an empty array on PostgreSQL (and possibly MySQL) re: https://stackoverflow.com/questions/43217100/make-sequelize-show-tables

The following `docker-compose` file will start a local copy of PostgreSQL to test against

```yml
version: "3.3"
services:
    postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh"
    ports:
      - "5432:5432"
```

This file should be 
 
```shell
#!/bin/sh

set -e

psql -v ON_ERROR_STOP=1 -U root <<-ESQL
  CREATE USER forge WITH PASSWORD 'secret';
  CREATE DATABASE flowforge;
  GRANT ALL PRIVILEGES ON DATABASE flowforge TO forge;
ESQL
```

### Environment

- FlowForge version: HEAD
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux/Docker
- Browser: na
