### ISSUE TITLE
Plausible script not injected

### ISSUE THREAD

**Issue by hardillb** [flowforge/flowforge#573]
### Current Behavior

After enabling Plausible analytics the script is not added to the page 

The following line is stripped out when the UI is built

https://github.com/flowforge/flowforge/blob/c6bd3fe7f2014239a20a0adaaa5f1c99001996f5/frontend/src/index.html#L11

### Expected Behavior

Script added to the page

### Steps To Reproduce

add following to `etc/flowforge.yml`

```yaml
tememetry:
  frontend:
    plausible:
      domain: example.com
```

Start the system

### Environment

- FlowForge version: 0.5.0
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: Linux/Docker
- Browser: All
